apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-tls-cert
spec:
  secretName: external-tls-cert
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
